/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ICourse {
  id: number;
  changedBy: string;
  changedAt: string;
  sId: number;
  ctId: number;
  name: string;
  lane?: string | null;
  capacity?: number | null;
  begin: string;
  end: string;
  seasonPass?: number;
  charge?: number | null;
  chargeNonMember?: number | null;
}
