/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ICourseParticipant {
  id: number;
  changedBy: string;
  changedAt: string;
  data_enc?: string;
  data?: {
    chargePayedAt?: string;
    [k: string]: any;
  };
  sId: number;
  cId: number;
  pId: number;
  instructor?: number;
  charge?: number | null;
  chargePayedAt?: null;
  familyDiscount?: number;
  passSent?: number;
  status?: number;
}
