/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ICourseTypeCheckList {
  id: number;
  changedBy?: string | null;
  changedAt?: string | null;
  ctId: number;
  item: string;
  order: number;
}
