/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IParticipant {
  id: number;
  changedBy: string;
  changedAt: string;
  data_enc: string;
  data: {
    lastName: string;
    firstName: string;
    birthdate?: string;
    sex?: string | null;
    street?: string | null;
    zipCode?: string | null;
    city?: string | null;
    phone?: string | null;
    phoneMobile?: string | null;
    phoneWork?: string | null;
    email?: string | null;
    altEmail?: string | null;
    emergencyContact?: string | null;
    altContact?: string | null;
    health?: string | null;
    membership?: number;
    dressSize?: string | null;
    relationId?: number | null;
    notes?: string | null;
  };
}
