/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IQualification {
  id: number;
  changedBy: string;
  changedAt: string;
  data_enc: string;
  data: {
    date?: string | null;
    notes?: string | null;
    status?: number | null;
    expiryDate?: string | null;
    renewalDate?: string | null;
    renewalCount?: number | null;
    renewalRegno?: string | null;
    examiner?: string | null;
    regno?: string | null;
  };
  pId: number;
  qtId: number;
}
