/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IRegistration {
  id: number;
  changedBy: string;
  changedAt: string;
  data_enc: string;
  data: {
    date: string;
    notes?: string | null;
    request?: string | null;
  };
  pId: number;
  ctId: number;
}
